### PR TITLE
Gen analysis

### PR DESCRIPTION
**Pull request by michaelmackenzie**
Add and update existing modules to store generator-level information. This includes the Z boson information (mass, pt, etc.), information about primary leptons (e.g. Z-->ll, WW-->ll), and number of (negative) events seen

### CODE REVIEW

**Review by gkaratha — COMMENTED** [review]
1) Not sure how we can match leptons if they dont have specific decay in mind. Are we not going to use reco matching?
2) Why not take the last copy of leptons?
3) What does the snipet in line 103 and downwards do?

**Comment by gkaratha** [comment]
I think if it runs in parallel with the other code should be fine. Otherwise acceptance calculation might become tricky

**Comment by michaelmackenzie** [comment]
> 1. Not sure how we can match leptons if they dont have specific decay in mind. Are we not going to use reco matching?
This isn't matching reco-objects to gen-objects, but identifies what decay of the Z occurred (Z->ee/mumu/tautau). It's useful for embedding, where we need the embedded di-tau kinematics for unfolding corrections, and for splitting the Drell-Yan sample into decay channels as well as correcting the Z (M, pT) spectrum

> 2. Why not take the last copy of leptons?
We need the embedded lepton kinematics for unfolding, as these correspond to the di-muon kinematics we're unfolding

> 3. What does the snipet in line 103 and downwards do?
In the Drell-Yan sample, there are many cases where the Z itself is not in the decay chain, and instead it starts with the di-lepton pair directly. We need to select the leptons correctly in this case, where we can reconstruct the Z mass and pT from the di-lepton pair for the Drell-Yan Z spectrum corrections

**Comment by michaelmackenzie** [comment]
> I think if it runs in parallel with the other code should be fine. Otherwise acceptance calculation might become tricky

There is no acceptance effect, as this does not filter out events unless specified to (which isn't done as of now, but I just added the option to match other modules)

**Comment by michaelmackenzie** [comment]
Also, for gen-reco matching, can we just use the NanoAOD supplied matching gen-particle for the reco objects? I believe this is `<Electron/Muon/Tau>_genPartIdx`, though I'm not exactly sure if this is as useful for hadronic tau decays (For the gen-level hadronic tau, I just take the mother tau p4 vector and subtract the neutrino p4 vectors)

**Comment by gkaratha** [comment]
> > 1. Not sure how we can match leptons if they dont have specific decay in mind. Are we not going to use reco matching?
> 
> This isn't matching reco-objects to gen-objects, but identifies what decay of the Z occurred (Z->ee/mumu/tautau). It's useful for embedding, where we need the embedded di-tau kinematics for unfolding corrections, and for splitting the Drell-Yan sample into decay channels as well as correcting the Z (M, pT) spectrum
>- I see that, my comment was mostly on how to match them in later step. If you dont know with which reco object to match then you cannot match

> > 2. Why not take the last copy of leptons?
> 
> We need the embedded lepton kinematics for unfolding, as these correspond to the di-muon kinematics we're unfolding
> -Still why not the last copy? this is the one to be reconstructed no?

> > 3. What does the snipet in line 103 and downwards do?
> 
> In the Drell-Yan sample, there are many cases where the Z itself is not in the decay chain, and instead it starts with the di-lepton pair directly. We need to select the leptons correctly in this case, where we can reconstruct the Z mass and pT from the di-lepton pair for the Drell-Yan Z spectrum corrections
>-ok

**Comment by gkaratha** [comment]
> Also, for gen-reco matching, can we just use the NanoAOD supplied matching gen-particle for the reco objects? I believe this is `<Electron/Muon/Tau>_genPartIdx`, though I'm not exactly sure if this is as useful for hadronic tau decays (For the gen-level hadronic tau, I just take the mother tau p4 vector and subtract the neutrino p4 vectors)

>-Never used it... How exactly gen/reco is matched?

**Comment by gkaratha** [comment]
> > I think if it runs in parallel with the other code should be fine. Otherwise acceptance calculation might become tricky
> 
> There is no acceptance effect, as this does not filter out events unless specified to (which isn't done as of now, but I just added the option to match other modules)

- Again I mean the acceptance/reco calculation not that your code affects it in some form. now to calculate efficiency i just do recoDR<0.X

**Comment by michaelmackenzie** [comment]
> > > 1. Not sure how we can match leptons if they dont have specific decay in mind. Are we not going to use reco matching?
> > 
> > 
> > This isn't matching reco-objects to gen-objects, but identifies what decay of the Z occurred (Z->ee/mumu/tautau). It's useful for embedding, where we need the embedded di-tau kinematics for unfolding corrections, and for splitting the Drell-Yan sample into decay channels as well as correcting the Z (M, pT) spectrum
> > 
> > * I see that, my comment was mostly on how to match them in later step. If you dont know with which reco object to match then you cannot match

Perhaps we can keep the current code that matches the gen-object to our selected reco-object? Here, I only use the output for Drell-Yan process splitting, Drell-Yan Z (M, pT) spectrum information, and Embedded di-tau kinematic information. The current code you've implemented might be better for gen-reco matched objects.

> 
> > > 2. Why not take the last copy of leptons?
> > 
> > 
> > We need the embedded lepton kinematics for unfolding, as these correspond to the di-muon kinematics we're unfolding
> > -Still why not the last copy? this is the one to be reconstructed no?

The embedded taus are not reconstructed, only visible decay products are. We want the taus embedded, before radiation, etc., for the unfolding as this corresponds to the muons that were embedded. The unfolding is accounting for the trigger and ID efficiencies for these muons, so we need the kinematics at input rather than later in the process chain (and same for the Z kinematics, we want the di-lepton info at Z decay to get the Z mass/pT before the leptons lose energy to FSR, etc.). If the Z is in the event list, we of course just use this info.

> 
> > > 3. What does the snipet in line 103 and downwards do?
> > 
> > 
> > In the Drell-Yan sample, there are many cases where the Z itself is not in the decay chain, and instead it starts with the di-lepton pair directly. We need to select the leptons correctly in this case, where we can reconstruct the Z mass and pT from the di-lepton pair for the Drell-Yan Z spectrum corrections
> > -ok

**Comment by michaelmackenzie** [comment]
> > Also, for gen-reco matching, can we just use the NanoAOD supplied matching gen-particle for the reco objects? I believe this is `<Electron/Muon/Tau>_genPartIdx`, though I'm not exactly sure if this is as useful for hadronic tau decays (For the gen-level hadronic tau, I just take the mother tau p4 vector and subtract the neutrino p4 vectors)
> 
> > -Never used it... How exactly gen/reco is matched?

Good question! I'm not actually sure, but I use this information and `<Object>_genPartFlav` when determining the gen-level information for the object (e.g. j-->tau_h or e-->tau_h information). The information in:
just gives "Index into genParticle list for MC matching to status==1 muons" for `Muon_genPartIdx` for example, but I can check in the workbook to see if there's better information

**Comment by michaelmackenzie** [comment]
> > > I think if it runs in parallel with the other code should be fine. Otherwise acceptance calculation might become tricky
> > 
> > 
> > There is no acceptance effect, as this does not filter out events unless specified to (which isn't done as of now, but I just added the option to match other modules)
> 
> * Again I mean the acceptance/reco calculation not that your code affects it in some form. now to calculate efficiency i just do recoDR<0.X

I would use different tools, e.g. the NanoAOD `genPartIdx` information or our own gen-particle matching for these studies. This gen-level information is really for information about the Z->ll(') decay rather than the gen-particle being reconstructed (e.g. it's the tau in Z->tau tau, not the decay product the tau decays to, that's being stored here).

**Comment by michaelmackenzie** [comment]
I made a figure from the 2018 Z MC to show the contribution of the Z and no-Z di-lepton events. It looks like the no-Z component is actually the gamma rather than the Z (except at high/low mass, where they seem to be combined)? We also see this shape in the 2018 signal MC, but all events have a Z parent in the signal MC (though we really shouldn't have the Z/gamma interference in the signal since we can better trust any gamma, mu, e coupling is not measureable for us).

Drell-Yan MC:
DY MC Z mass

Signal MC:
Signal MC Z mass

**Pull request merged**
